# @package _global_

defaults:
  - /env/decoupled_locomotion_stand_height_waist_wbc_ma_diff_force_no_residual@_here_
  - _self_

env:
  _target_: humanoidverse.envs.decoupled_locomotion.decoupled_locomotion_stand_height_waist_wbc_ma_hand_pose.LeggedRobotDecoupledLocomotionStanceHeightWBCForceHandPose
